import { createFileRoute } from "@tanstack/react-router";
import { useEffect, useState } from "react";
import { useServerFn } from "@tanstack/react-start";
import { generateDailyQuests, type Quest } from "@/lib/ai.functions";
import { supabase } from "@/integrations/supabase/client";
import { useAuth } from "@/hooks/use-auth";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Checkbox } from "@/components/ui/checkbox";
import { Badge } from "@/components/ui/badge";
import { Loader2, Sparkles, Target, Clock, Trophy } from "lucide-react";
import { toast } from "sonner";

export const Route = createFileRoute("/_authenticated/quests")({
  head: () => ({ meta: [
    { title: "Daily Glow Quests · GlowQuest AI" },
    { name: "description", content: "Personalized daily wellness quests generated by AI." },
    { property: "og:title", content: "Daily Glow Quests · GlowQuest AI" },
    { property: "og:description", content: "Complete quests, earn XP, grow your glow." },
  ] }),
  component: Quests,
});

function Quests() {
  const { user } = useAuth();
  const gen = useServerFn(generateDailyQuests);
  const [quests, setQuests] = useState<Quest[]>([]);
  const [loading, setLoading] = useState(false);
  const today = new Date().toISOString().slice(0, 10);

  useEffect(() => {
    if (!user) return;
    supabase.from("daily_glow_quests").select("quests").eq("user_id", user.id).eq("date", today).maybeSingle()
      .then(({ data }) => { if (data?.quests) setQuests(data.quests as unknown as Quest[]); });
  }, [user, today]);

  const onGenerate = async () => {
    setLoading(true);
    try {
      const res = (await gen()) as { quests: Quest[] };
      setQuests(res.quests);
      toast.success("Quests generated!");
    } catch (e) {
      toast.error(e instanceof Error ? e.message : "Failed");
    } finally { setLoading(false); }
  };

  const toggle = async (id: string) => {
    if (!user) return;
    const next = quests.map((q) => q.id === id ? { ...q, completed: !q.completed } : q);
    setQuests(next);
    await supabase.from("daily_glow_quests").upsert(
      { user_id: user.id, date: today, quests: next as unknown as never },
      { onConflict: "user_id,date" },
    );
  };

  const done = quests.filter((q) => q.completed).length;
  const total = quests.length;
  const xp = quests.filter((q) => q.completed).reduce((s, q) => s + (q.xp ?? 0), 0);
  const pct = total ? Math.round((done / total) * 100) : 0;

  return (
    <div className="space-y-6">
      <Card className="rounded-3xl border-0 bg-glow-gradient text-primary-foreground shadow-glow">
        <CardHeader>
          <CardTitle className="flex items-center gap-2 font-display text-2xl">
            <Target className="h-6 w-6" /> Daily Glow Quests
          </CardTitle>
        </CardHeader>
        <CardContent className="flex flex-wrap items-center justify-between gap-3">
          <div className="flex gap-4 text-sm">
            <span className="flex items-center gap-1"><Trophy className="h-4 w-4" /> {xp} XP earned</span>
            <span>{done}/{total} • {pct}%</span>
          </div>
          <Button onClick={onGenerate} disabled={loading} variant="secondary" className="rounded-full">
            {loading ? <Loader2 className="mr-2 h-4 w-4 animate-spin" /> : <Sparkles className="mr-2 h-4 w-4" />}
            {quests.length ? "Regenerate" : "Generate today's quests"}
          </Button>
        </CardContent>
      </Card>

      <div className="grid gap-3 md:grid-cols-2">
        {quests.map((q) => (
          <Card key={q.id} className={"rounded-2xl transition " + (q.completed ? "opacity-70" : "")}>
            <CardContent className="p-4 flex gap-3">
              <Checkbox checked={q.completed} onCheckedChange={() => toggle(q.id)} className="mt-1" />
              <div className="flex-1">
                <div className="flex items-center justify-between gap-2">
                  <h3 className={"font-medium " + (q.completed ? "line-through text-muted-foreground" : "")}>{q.title}</h3>
                  <Badge variant="secondary" className="rounded-full">+{q.xp} XP</Badge>
                </div>
                <p className="text-sm text-muted-foreground mt-1">{q.description}</p>
                <div className="mt-2 flex gap-3 text-xs text-muted-foreground">
                  <span className="flex items-center gap-1"><Clock className="h-3 w-3" />{q.estimatedMinutes} min</span>
                  <span className="capitalize">• {q.difficulty}</span>
                </div>
              </div>
            </CardContent>
          </Card>
        ))}
        {quests.length === 0 && !loading && (
          <Card className="rounded-2xl border-dashed md:col-span-2">
            <CardContent className="p-8 text-center text-muted-foreground">
              No quests yet — hit <strong>Generate today's quests</strong> to get started.
            </CardContent>
          </Card>
        )}
      </div>
    </div>
  );
}
